[package]
name = "bullet_lib"
version = "1.0.0"
edition = "2021"
rust-version = "1.83"
description = "Neural Network Trainer"
authors = ["Jamie Whiting"]
license = "MIT"
repository = "https://github.com/jw1912/bullet"
readme = "README.md"
build = "build/main.rs"

[features]
cudnn = []
hip = []
gh-actions = []

[dependencies]
bulletformat = { workspace = true }
rand = "0.8.5"
rand_distr = "0.4.3"
sfbinpack = { package = "binpack", git = "https://github.com/Disservin/binpack-rust" }

[build-dependencies]
cc = "1.2.5"

[workspace]
resolver = "2"
members = ["utils"]

[workspace.package]
license = "MIT"
authors = ["Jamie Whiting"]

[workspace.dependencies]
bulletformat = "1.7.0"

[profile.release]
debug = true
codegen-units = 1
lto = true
